<a href="https://colab.research.google.com/github/vaneesa-writes/parctice/blob/main/38_IMLexp2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A) Expected value 

In [ ]:
import numpy as np
def exp_val(values,probabilities):
  return sum([v*p for v,p in zip(values,probabilities)])
print("Exected Value:",exp_val([2,3,4],[0.2,0.3,0.5]))

Exected Value: 3.3


B) Mean

In [ ]:
n=np.arange(1,11)
print(n)
#np.mean gives you the mean of n elements 
print("Mean Value:",np.mean(n))
print("Average Value:",np.average(n))

[ 1  2  3  4  5  6  7  8  9 10]
Mean Value: 5.5
Average Value: 5.5


c)standard deviation

In [ ]:
n=np.arange(1,10)
print(n)
#np.std gives you the standard deviation of an numpy array 
print("Standard Deviation:",np.std(n))

[1 2 3 4 5 6 7 8 9]
Standard Deviation: 2.581988897471611


d)variance

In [ ]:
n=np.arange(0,10)
print(n)
#np.var gives you the variance of elements in a numpy array
print("Variance:",np.var(n))

[0 1 2 3 4 5 6 7 8 9]
Variance: 8.25


c)covariance

In [ ]:
x=np.array([1,2,3,4])
#np.cov gives you the covariance of an numpy array
print("Covariance",np.cov(x))

Covariance 1.6666666666666665


f) covariance with two arrays \\

In [ ]:
x=np.array([0,1,2])
y=np.array([2,1,0])
print("Array one")
print(x)
print("\nArray two")
print(y)
print("\nCovariance using two matrix")
#we can also calculate the covariance of two arrays using np.cov
print(np.cov(x,y))

Array one
[0 1 2]

Array two
[2 1 0]

Covariance using two matrix
[[ 1. -1.]
 [-1.  1.]]
